name: coc_bases
description: "Clash of Clans Bases"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/bg-image.png
    - assets/townhall-card.png
    - assets/app-icon.png

    - assets/townhall/th4.png
    - assets/townhall/th5.png
    - assets/townhall/th6.png
    - assets/townhall/th7.png
    - assets/townhall/th8.png
    - assets/townhall/th9.png
    - assets/townhall/th10.png
    - assets/townhall/th11.png
    - assets/townhall/th12.png
    - assets/townhall/th13.png
    - assets/townhall/th14.png
    - assets/townhall/th15.png
    - assets/townhall/th16.png
    - assets/townhall/th17.png

    - assets/builderhall/bh4.png
    - assets/builderhall/bh5.png
    - assets/builderhall/bh6.png
    - assets/builderhall/bh7.png
    - assets/builderhall/bh8.png
    - assets/builderhall/bh9.png
    - assets/builderhall/bh10.png
  #   - images/a_dot_ham.jpeg

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/app-icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app-icon.png"
    background_color: "#ffffff"  # white background
    theme_color: "#006D62" 

  # fonts:
  #   - family: TimesNewRoman
  #     fonts:
  #       - asset: assets/fonts/Tinos-Regular.ttf
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700